_target_: src.criterions.sinr_loss.SinrANFull

pos_weight: 2048
bounds:
  { "north": 71.18392, "south": 34.56858, "west": -10.53904, "east": 34.55792 }
batch_size: ${data.batch_size}
num_workers: ${data.num_workers}
pin_memory: ${data.pin_memory}
num_saved_batches: 256
