_target_: src.criterions.sinr_loss.SinrANFull

pos_weight: 2048
bounds:
  { "north": 71.18392, "south": 34.56858, "west": -10.53904, "east": 34.55792 }
batch_size: 2048
num_workers: 16
pin_memory: False
num_saved_batches: 256
