defaults:
  - /criterions@criterion:
    - cross_entropy_loss

_target_: src.models.log_reg.LogReg

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.single_linear.SingleLinear
  input_size: 4
  output_size: 10040

# compile model for faster training with pytorch 2.0
compile: false
