defaults:
  - /criterions@criterion:
      - sinr_an_full_europe

_target_: src.models.sinr_module.SINRModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0007
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.sinr_net.SinrNet
  input_dim: 4
  hidden_dim: 512
  num_blocks: 8
  output_classes: 10040
  dropout: 0.3

# compile model for faster training with pytorch 2.0
compile: false
threshold: 0.7
